### ISSUE TITLE
Make installa fallisce su Mac OS X

### ISSUE THREAD

**Issue by matteo-l** [GuITeX/guidatematica#11]
La versione di cp installata su Mac OS X non supporta l'opzione '-u', di conseguenza l'installazione fallisce con il messaggio d'errore: "cp: illegal option -- u"

**Comment by robitex** [comment]
Ciao Matteo.
Con la nuova versione v2.2.00 ho modificato il makefile eliminando l'opzione -u.
Penso che dovrebbe funzionare adesso (meglio tardi che mai).
Grazie.

**Comment by matteo-l** [comment]
Funziona, almeno sulla vecchia versione di Mac OS che ho a disposizione (10.11).

**Comment by robitex** [comment]
Grazie mille Matteo.
